# Generated by Django 6.0.5 on 2026-06-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_project_projectmodule_delete_sensordata"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="max_errors",
            field=models.PositiveIntegerField(
                default=3, help_text="Maximum allowed errors before game over"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="story_image",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
        migrations.AddField(
            model_name="projectmodule",
            name="story_image",
            field=models.ImageField(blank=True, null=True, upload_to="module_images/"),
        ),
    ]
