# Generated by Django 6.0.5 on 2026-06-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_projectimage_projectmoduleimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="time_limit",
            field=models.PositiveIntegerField(
                default=3600, help_text="Global time limit in seconds"
            ),
        ),
    ]
