# Generated by Django 6.0.5 on 2026-06-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_project_time_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="failure_image",
            field=models.ImageField(
                blank=True,
                help_text="Custom image shown on failure",
                null=True,
                upload_to="project_results/",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="failure_text",
            field=models.TextField(
                blank=True, help_text="Custom text shown on failure", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="success_image",
            field=models.ImageField(
                blank=True,
                help_text="Custom image shown on success",
                null=True,
                upload_to="project_results/",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="success_text",
            field=models.TextField(
                blank=True, help_text="Custom text shown on success", null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectmodule",
            name="module_type",
            field=models.IntegerField(
                choices=[
                    (1, "方向指令模組"),
                    (2, "鑰匙模組"),
                    (3, "調頻模組"),
                    (4, "RGB模組"),
                    (5, "摩斯密碼模組"),
                    (6, "旋鈕模組"),
                    (7, "密碼模組"),
                    (8, "拆線模組"),
                    (9, "符號指撥開關模組"),
                ]
            ),
        ),
    ]
