# Generated by Django 6.0.5 on 2026-06-10 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_project_failure_image_project_failure_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="failure_image",
        ),
        migrations.RemoveField(
            model_name="project",
            name="success_image",
        ),
        migrations.CreateModel(
            name="ProjectFailureImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="project_failure/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_images",
                        to="mainapp.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSuccessImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="project_success/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="success_images",
                        to="mainapp.project",
                    ),
                ),
            ],
        ),
    ]
